VERSIONING="2.0.0"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
FEDERATION_SERVER="https://api.stellar.org/federation"
AUTH_SERVER="https://api.stellar.org/auth"
TRANSFER_SERVER="https://api.stellar.org/auth"
SIGNING_KEY="GDDBWGSAEG4OXKCHJCKPI2LDMYHOTHR4NPKJSBR7FQVQZKAPNVJ324KE"
HORIZON_URL="https://horizon.stellar.org"

ACCOUNTS=["GACJHFU3IAV2IYUQ5PLNA4TJQJHAFKFCCOWZVYSBG4RBEEHMH7P3E4CF",
"GDDBWGSAEG4OXKCHJCKPI2LDMYHOTHR4NPKJSBR7FQVQZKAPNVJ324KE"]


[DOCUMENTATION]

ORG_NAME="Luxury Yacht Coin"
ORG_URL="https://umbrella-intwaters.pages.dev/"
ORG_LOGO=""
ORG_DESCRIPTION=""



 








ORG_PHYSICAL_ADDRESS="United States"
ORG_PHYSICAL_ADDRESS_ATTESTATION=""
ORG_PHONE_NUMBER=""
ORG_PHONE_NUMBER_ATTESTATION=""
ORG_KEYBASE="YHTS7S"
ORG_TWITTER=""
ORG_GITHUB=""
ORG_OFFICIAL_EMAIL=""

[[PRINCIPALS]]

name="saas"
email=""
keybase=""
twitter=""
github=""
id_photo_hash=""
verification_photo_hash=""

[[CURRENCIES]]
code="YHTS"
issuer="GCWDIWJCFUW2ZBF4V4PUJFQBOGDWN7HK2RTNNVLBHY5R4CFBP27HE432"
display_decimals=4
attestation_of_reserve="https://stellar.expert/explorer/public/market?asset=YHTS-GCWDIWJCFUW2ZBF4V4PUJFQBOGDWN7HK2RTNNVLBHY5R4CFBP27HE432"
name="Luxury Yahct Coin"
desc="Fungible utility token."
conditions="Verified mint. Active burn policy. Issuer may mint additional tokens."
image="https://umbrella-intwaters.pages.dev/PSX_20220803_151110.jpg"
fixed_number="1000000.37"


