VERSIONING="2.0.0"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
FEDERATION_SERVER="https://api.stellar.org/federation"
AUTH_SERVER="https://api.stellar.org/auth"
TRANSFER_SERVER="https://api.stellar.org/auth"
SIGNING_KEY="GDDBWGSAEG4OXKCHJCKPI2LDMYHOTHR4NPKJSBR7FQVQZKAPNVJ324KE"
HORIZON_URL="https://horizon.stellar.org"

ACCOUNTS=["GACJHFU3IAV2IYUQ5PLNA4TJQJHAFKFCCOWZVYSBG4RBEEHMH7P3E4CF",
"GDDBWGSAEG4OXKCHJCKPI2LDMYHOTHR4NPKJSBR7FQVQZKAPNVJ324KE",
"GAOHXQHKM2F5YW7XOTBOOUCNOE5P5G6OUBJJWZP7AA3G3JD3DYDCNZJY"]


[DOCUMENTATION]

ORG_NAME="Luxury Yacht Coin"
ORG_URL="https://umbrella-intwaters.pages.dev/"
ORG_LOGO="https://umbrella-intwaters.pages.dev/PSX_20220803_155454.jpg"
ORG_DESCRIPTION="Fungible cryptocurrency"



 








ORG_PHYSICAL_ADDRESS="United States"
ORG_PHYSICAL_ADDRESS_ATTESTATION=""
ORG_PHONE_NUMBER=""
ORG_PHONE_NUMBER_ATTESTATION=""
ORG_KEYBASE="YHTS7S"
ORG_TWITTER=""
ORG_GITHUB="https://umbrella-intwaters.pages.dev"
ORG_OFFICIAL_EMAIL=""

[[PRINCIPALS]]

name="saas"
email=""
keybase=""
twitter=""
github=""
id_photo_hash=""
verification_photo_hash=""



[[CURRENCIES]]
code="YHTS"
issuer="GDDBWGSAEG4OXKCHJCKPI2LDMYHOTHR4NPKJSBR7FQVQZKAPNVJ324KE"
display_decimals=4
attestation_of_reserve="https://stellar.expert/explorer/public/asset/YHTS-GDDBWGSAEG4OXKCHJCKPI2LDMYHOTHR4NPKJSBR7FQVQZKAPNVJ324KE-1?filter=markets"
name="Luxury Yahct Coin"
desc="Fungible utility token."
conditions="Verified mint. Active burn policy. Issuer may mint additional tokens."
image="https://umbrella-intwaters.pages.dev/PSX_20220803_151110.jpg"
fixed_number="1000000.01"
[[CURRENCIES]]
code="YHTS"
issuer="GC3YRTJQUXVQMG5STS7MSWVF3OF3Z5MVF6NEWZLKNQAJZX5UUFLMCFMA"
display_decimals=4
attestation_of_reserve="https://stellar.expert/explorer/public/asset/YHTS-GC3YRTJQUXVQMG5STS7MSWVF3OF3Z5MVF6NEWZLKNQAJZX5UUFLMCFMA-1?filter=markets"
name="Luxury Yahct Coin"
desc="Fungible utility token."
conditions="Verified mint. Active burn policy. Issuer may mint additional tokens."
image="https://umbrella-intwaters.pages.dev/PSX_20220803_151110.jpg"
fixed_number="9999.99"

[[CURRENCIES]]

code="AQUAPOD"

issuer="GBBT7SR6TODAKWJDG3NJEARPRQEDKO6AAR35Q36YQZP6367FQASLLW3F"

display_decimals=4

attestation_of_reserve="https://stellar.expert/explorer/public/asset/AQUAPOD-GBBT7SR6TODAKWJDG3NJEARPRQEDKO6AAR35Q36YQZP6367FQASLLW3F?filter=markets&market=SDEXEX-GBQHMDRWV3WU5YACBUUCBY4Y6PPWBJXW5WCSG5XJ63FC4HXJNGXYFD5J-2"
name="Aquapod"

desc="Fungible utility token."

conditions="Verified mint. Active burn policy. Issuer may mint additional tokens."

image="https://umbrella-intwaters.pages.dev/aquapod.jpg"

fixed_number="999999"
[[CURRENCIES]]
code="AQUAPODASSOC"
issuer="GBBT7SR6TODAKWJDG3NJEARPRQEDKO6AAR35Q36YQZP6367FQASLLW3F"
display_decimals=4
attestation_of_reserve="https://stellar.expert/explorer/public/asset/AQUAPODASSOC-GBBT7SR6TODAKWJDG3NJEARPRQEDKO6AAR35Q36YQZP6367FQASLLW3F?filter=markets&market=SDEXEX-GBQHMDRWV3WU5YACBUUCBY4Y6PPWBJXW5WCSG5XJ63FC4HXJNGXYFD5J-2"
name="Aquapod Associatuon"
desc="Fungible utility token."
conditions="Verified mint. Active burn policy. Issuer may mint additional tokens."
image="https://umbrella-intwaters.pages.dev/aquapod.jpg"
fixed_number="1000000000"
